### ISSUE TITLE
icenet_plot_sie_error seems to have internally broken function call

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet#129]
* IceNet version: 0.2.2

### Description

Running the command, there seems to be a mapping error if no threshold is supplied from the CLI

### What I Did

```
icenet_plot_sie_error -r "125,190,170,235" -e -b       -o sie_error.test.png       north results/predict/lanc23.2023-02-18_north.nc 2022-02-18
...
Traceback (most recent call last):
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet/bin/icenet_plot_sie_error", line 8, in <module>
    sys.exit(sie_error())
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet-new/lib/python3.8/site-packages/icenet/plotting/forecast.py", line 1305, in sie_error
    plot_sea_ice_extent_error(masks=masks,
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet-new/lib/python3.8/site-packages/icenet/plotting/forecast.py", line 286, in plot_sea_ice_extent_error
    forecast_sie_error = compute_sea_ice_extent_error(masks=masks,
TypeError: compute_sea_ice_extent_error() missing 1 required positional argument: 'threshold'
```

**Comment by JimCircadian** [comment]
@rchan26 I think this might have been introduced, potentially, when we had to merge overlapped changes into 0.2.2?
