### ISSUE TITLE
Fresh download of OSISAF fails

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet#132]
* IceNet version: 0.2.3

### Description

Reseeding the 1979-2023 data store at BAS, it fails because the source data is missing latitudes. I removed the fix for this long ago thinking it was sorted in the OSISAF data, but not sure why. D'oh!

### What I Did

```
icenet_data_sic north 1979-1-1 2023-2-28 
....
Traceback (most recent call last):
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet/bin/icenet_data_sic", line 8, in <module>
    sys.exit(main())
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet-new/lib/python3.8/site-packages/icenet/data/sic/osisaf.py", line 543, in main
    sic.download()
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet-new/lib/python3.8/site-packages/icenet/data/sic/osisaf.py", line 391, in download
    raise RuntimeError("latitude missing, fix required that has "
RuntimeError: latitude missing, fix required that has been removed in this version
```

**Comment by JimCircadian** [comment]
I've taken to just downloading a spare file for the coordinates to come from on a single basis, it's far easier and more likely to work than fringe cases that mean that the data being downloaded might not have the coordinates required. Extended also to include both lat and lon for defensiveness
