### ISSUE TITLE
WandB is causing evaluation problems / reporting failures

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet#154]
* IceNet version: 0.2.3

### Description

Running an ensemble, the evaluation fails for two reasons

1. [x] The evaluation seems to be using the validation set rather than the test set
2. [x] The evaluation metrics upload didn't seem to work
3. [x] Some unexpected nans, pfft

This code should be review, but certainly `PermissionDenied` suggest the initialisation of wandb has dropped out as that should be sorted via the runtime environment (the upload of the run worked fine, so suggests there is another issue with the wandb library causing this.) 

### What I Did

```
[28-04-23 07:23:52 :INFO    ] - Training dataset(s) marked to be shuffled
[28-04-23 07:23:52 :WARNING ] - Using validation data source for evaluation, rather than test set
[28-04-23 07:23:52 :INFO    ] - Metric creation for lead time of 93 days
[28-04-23 07:23:52 :INFO    ] - Evaluating... 
[28-04-23 07:24:45 :DEBUG   ] - {'loss': 0.0, 'binacc1': 98.71408081054688, 'mae1': 1.7787102460861206, 'rmse1': 3.34605
43155670166, 'binacc2': 98.43955993652344, 'mae2': 2.1851611137390137, 'rmse2': 4.310390949249268, 'binacc3': 97.9851150
...
.884270668029785, 'rmse90': 19.16646385192871, 'binacc91': 90.83219146728516, 'mae91': 8.878358840942383, 'rmse91': 19.1
32265090942383, 'binacc92': nan, 'mae92': nan, 'rmse92': nan, 'binacc93': nan, 'mae93': nan, 'rmse93': nan}
...
[28-04-23 07:24:45 :INFO    ] - Done in 52.7s
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: - 0.007 MB of 0.007 MB uploaded (0.000 MB deduped)^Mwandb: \ 0.007 MB of 0.063 MB uploaded (0.000 MB deduped)^Mwa
...
wandb: <U+1F680> View run atmos23_south.42 at: https://wandb.ai/jambyr/yellow/runs/dla9p36x
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230427_232045-dla9p36x/logs
Traceback (most recent call last):
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet/bin/icenet_train", line 33, in <module>
    sys.exit(load_entry_point('icenet', 'console_scripts', 'icenet_train')())
  File "/data/hpcdata/users/jambyr/icenet/icenet/icenet/model/train.py", line 443, in main
    evaluate_model(model_path,
  File "/data/hpcdata/users/jambyr/icenet/icenet/icenet/model/train.py", line 328, in evaluate_model
    wandb.log(
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet-new/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper
...
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet-new/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/users'
```

**Comment by JimCircadian** [comment]
This is most likely down to the loss of scope with the wandb object, as initialisation is happening within the `train_model` method. Therefore calling log without a second `wandb.init` causes the failure as the `wandb` tries to create directories that can't exist due to the default initialisation state. 

This relates to the developments of #83 and #86, both of which in short are annoyances caused by the strong link to wandb usage. I'm going to address all three issues to make wandb very much optional (and off by default)

**Comment by JimCircadian** [comment]
Reworked all the wandb stuff to remove the integration with `train_model` and `evaluate_model`, as well as be happy without it's presence and not be a dependency for installation
