### ISSUE TITLE
Still getting wandb logging issues

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet#168]
* IceNet version: 0.2.5

### Description

Running an ensemble, the output evaluation metrics for a test run still aren't logging. Again this is an issue with wandb de-init'ing, probably because of an odd scope issue. It's a real headache because so many activities take place against the module.

### What I Did

```
# Run an ensemble
# No metrics uploaded

# Investigate run logs and find
wandb: Find logs at: ./wandb/run-20230710_121450-qhw3ase4/logs
Traceback (most recent call last):
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet/bin/icenet_train", line 33, in <module>
    sys.exit(load_entry_point('icenet', 'console_scripts', 'icenet_train')())
  File "/data/hpcdata/users/jambyr/icenet/icenet/icenet/model/train.py", line 458, in main
    wandb.log(
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet-new/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper
...
PermissionError: [Errno 13] Permission denied: '/users'
```

This happens due to the default init against the module being invoked because the previous init call, I assume, lost scope: that scope had the correct configuration which points the config lookup not to `/users` but to a dedicated configuration (a quirk of our HPC)...

**Comment by JimCircadian** [comment]
Still getting the error after the attempt to revise the situation with that commit (which to be fair is a bit nicer anyway because it places the imports at the top of the script.) Upgrading wandb, to see if that makes any difference...
