### ISSUE TITLE
parallel-opens CLI arg is conflicting with existing args

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet#185]
* IceNet version: 0.2.6

### Description

Good case for unit testing (or at least restructuring the CLI argument setup to be clearer!) New parallel-opens argument causes an error due to conflicting argument 

### What I Did

`icenet_data_era5` tries to add `-p` when it is already in place due to the recently added parallel-opens option

```
Traceback (most recent call last):
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet/bin/icenet_data_era5", line 33, in <module>
    sys.exit(load_entry_point('icenet', 'console_scripts', 'icenet_data_era5')())
  File "/data/hpcdata/users/jambyr/icenet/icenet/icenet/data/interfaces/cds.py", line 263, in main
    args = download_args(choices=["cdsapi", "toolbox"],
  File "/data/hpcdata/users/jambyr/icenet/icenet/icenet/utils.py", line 83, in wrapper
    parsed_args = func(*args, **kwargs)
  File "/data/hpcdata/users/jambyr/icenet/icenet/icenet/data/cli.py", line 144, in download_args
    ap.add_argument(*arg[0], **arg[1])
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet-new/lib/python3.8/argparse.py", line 1386, in add_argument
    return self._add_action(action)
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet-new/lib/python3.8/argparse.py", line 1749, in _add_action
    self._optionals._add_action(action)
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet-new/lib/python3.8/argparse.py", line 1590, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet-new/lib/python3.8/argparse.py", line 1400, in _add_action
    self._check_conflict(action)
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet-new/lib/python3.8/argparse.py", line 1539, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet-new/lib/python3.8/argparse.py", line 1548, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -p/--do-not-postprocess: conflicting option string: -p
```

**Comment by bnubald** [comment]
Thoughts on enabling `conflict_handler` flag on ArgumentParser call.

This would allow overriding arguments previously defined with the same flag - if that is the intention (Doesn't seem to be the case with this specific error, but maybe useful for similar calls to `download_args()` in future?).

```python
ap = argparse.ArgumentParser(conflict_handler = 'resolve')
```

here:

https://github.com/icenet-ai/icenet/blob/c573671b2ec8759d633b35d2987318e3552d50c1/icenet/data/cli.py#L108

Referencing argparse Python 3.8.x-3.12.x docs:
https://docs.python.org/3.8/library/argparse.html#conflict-handler

___

Caveat with this approach is that it will not cover all scenarios.

One example of caveat would be considering the error above, where `-p` and `--parallel-opens` have been initially defined in v0.2.6, and let's say we wanted to overwite both the short and its corresponding long flags. If this is the initial definition:
```python
    ap.add_argument("-p", "--parallel-opens",
                    default=False, action="store_true",
                    help="Allow xarray mfdataset to work with parallel opens")
```

Enabling the flag will not cause both the short and corresponding long flags to be overwritten if only one of them is redefined. E.g., adding new argument with same short `-p` flag, but different long `--do-no-postprocess` flag:

```python
    ap.add_argument("-p", "--do-not-postprocess",
                    default=False, action="store_true")
```

The original `-p` will be overwritten, but `--parallel-opens` will remain since the new long arg is different -> `--do-not-postprocess`.

So, the args supported will now be `-p` (corresponding to the last definition in control flow), `--parallel-opens`, and `--do-not-postprocess`.
