### ISSUE TITLE
UNet channel dimension: Some n_filters_factor multiplication causing error

### ISSUE THREAD

**Issue by bnubald** [icenet-ai/icenet#209]
* IceNet version: v0.2.7_dev
* Python version: 3.11

### Description

Running with certain `n_filters_factor` causes mismatching channel dimensions. E.g. `n_filters_factor = 0.3` and `n_filters_factor = 0.6`. Using values of 0.5 or not setting it doesn't cause issue.

Believe this to be due to Python's bankers rounding approach.

When the channel dimension is multiplied by this factor, and the result is a value which is rounded to the nearest even value - result becomes inconsistent depending on input value to `int()`.

### What I Did

Omitting stdout for successful commands:

Note n_filters_factor=0.3 is the change causing the error compared to 0.5, or 1.0 which runs without issue.

```bash
$ icenet_data_masks south
$ icenet_data_era5 south -d --vars uas,vas,tas,zg --levels ',,,500|250' 2020-1-1 2020-4-30
$ icenet_data_sic south -d 2020-1-1 2020-4-30
$ icenet_process_era5 notebook_tf_data south -ns 2020-1-1 -ne 2020-3-31 -vs 2020-4-3 -ve 2020-4-23 -ts 2020-4-1 -te 2020-4-2 -l 1 --abs uas,vas --anom tas,zg500,zg250
$ icenet_process_sic notebook_tf_data south -ns 2020-1-1 -ne 2020-3-31 -vs 2020-4-1 -ve 2020-4-20 -ts 2020-4-1 -te 2020-4-2 -l 1 --abs siconca
$ icenet_process_metadata notebook_tf_data south
$ icenet_dataset_create -l 1 -fd 7 -ob 2 -w 4 notebook_tf_data south
$ icenet_train notebook_tf_data notebook_tf_testrun 42 -b 4 --epochs 10 --multiprocessing --max-queue-size 4 --workers 4 --n-filters-factor 0.3 --no-wandb
$ ./loader_test_dates.sh notebook_tf_data | tee testdates.csv
$ icenet_predict -n 0.3 -t notebook_tf_data notebook_tf_testrun example_south_tf_forecast 42 testdates.csv
```

Traceback on last command:
```bash
[31-12-23 18:51:42 :INFO    ] - Loading configuration ./dataset_config.notebook_tf_data.json
[31-12-23 18:51:42 :INFO    ] - Training dataset path: ./network_datasets/notebook_tf_data/south/train
[31-12-23 18:51:42 :INFO    ] - Validation dataset path: ./network_datasets/notebook_tf_data/south/val
[31-12-23 18:51:42 :INFO    ] - Test dataset path: ./network_datasets/notebook_tf_data/south/test
[31-12-23 18:51:42 :INFO    ] - Loading configuration /git/icenet/notebook-pipeline/loader.notebook_tf_data.json
[31-12-23 18:51:42 :INFO    ] - Loading model from ./results/networks/notebook_tf_testrun/notebook_tf_testrun.network_notebook_tf_data.42.h5...
Traceback (most recent call last):
  File "/miniconda3/envs/pytorch/bin/icenet_predict", line 33, in <module>
    sys.exit(load_entry_point('icenet', 'console_scripts', 'icenet_predict')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/git/icenet/icenet/icenet/model/predict.py", line 198, in main
    predict_forecast(
  File "/git/icenet/icenet/icenet/model/predict.py", line 66, in predict_forecast
    network.load_weights(network_path)
  File "/miniconda3/envs/pytorch/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/miniconda3/envs/pytorch/lib/python3.11/site-packages/keras/src/backend.py", line 4359, in _assign_value_to_variable
    variable.assign(value)
ValueError: Cannot assign value to variable ' conv2d_4/kernel:0': Shape mismatch.The variable shape (3, 3, 76, 153), and the assigned value shape (152, 76, 3, 3) are incompatible.
```

**Comment by bnubald** [comment]
Issue with scaling channel dimension by n_filters_factor.

Based on traceback, issue likely to be where channel dimension is set to `512` (`0.3*512 = 153.6`), error shows `153`, or where it is taken as an input to the next layer:

https://github.com/icenet-ai/icenet/blob/ea3c3a7528b419e409e59ee6c0db35397606ef2d/icenet/model/models.py#L113-L138

**Comment by bnubald** [comment]
Basic working example representing issue:

```python
n_filters_factor = 0.3
channels = [64, 128, 256, 512]

# Multiply each element by n_filters_factor
channels_times_nfac = [c*n_filters_factor for c in channels]

# Cast floats to ints
int_channels_nfac = [int(c*n_filters_factor) for c in channels]

# Multiply each by 2 for shape conv2d is expecting
int_channels_nfac_x2 = [2*c for c in int_channels_nfac][:-1]
int_channels_nfac_x2.insert(0, int_channels_nfac[0])

print(channels_times_nfac)
print(int_channels_nfac)
print(int_channels_nfac_x2)
```

Output:

```bash
[19.2, 38.4, 76.8, 153.6]
[19, 38, 76, 153]
[19, 38, 76, 152]
```

Looks like could be because of upsampling a layer by 2, culprit does still seem to boil down to rounding causing difference in values.

**Comment by bnubald** [comment]
Using multiple of base `64*n_filters_factor` for input channels should fix issue.

Example:
```python
n_filters_factor = 0.3
start_out_channels = 64
reduced_channels = int(start_out_channels*n_filters_factor)
channels = {}
for pow in range(4):
    value = reduced_channels*2**pow
    channels[start_out_channels*2**pow] = value

print(channels)
```

Output:
`{64: 19, 128: 38, 256: 76, 512: 152}`
