### ISSUE TITLE
Predictions for old 0.2 models failing

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet#236]
* IceNet version: 0.2.7+

### Description

Predictions on a daily basis, standard procedure with pipelines run_era5_forecast

### What I Did

Predictions via the pipeline are failling with a weight loading error. This **does not** occur with 0.2.6 so far as I can tell, but was introduced via 0.2.7

```
[10-04-24 12:19:04 :DEBUG   ] - Creating converter from 3 to 5
Traceback (most recent call last):
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet/bin/icenet_predict", line 33, in <module>
    sys.exit(load_entry_point('icenet', 'console_scripts', 'icenet_predict')())
  File "/data/hpcdata/users/jambyr/icenet/icenet2/icenet/model/predict.py", line 198, in main
    predict_forecast(
  File "/data/hpcdata/users/jambyr/icenet/icenet2/icenet/model/predict.py", line 66, in predict_forecast
    network.load_weights(network_path)
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet27/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet27/lib/python3.8/site-packages/keras/src/backend.py", line 4361, in _assign_value_to_variable
    variable.assign(value)
ValueError: Cannot assign value to variable ' conv2d_8/kernel:0': Shape mismatch.The variable shape (3, 3, 368, 736), and the assigned value shape (737, 368, 3, 3) are incompatible.

**Comment by JimCircadian** [comment]
The number of channels calculated now differs based on channels_dict. Easy mistake, as the n_filters_factor is real and the rounding needs to be applied at the last moment

![image](https://github.com/icenet-ai/icenet/assets/731727/f91be043-5e25-486f-99d9-80c7e28df577)

**Comment by JimCircadian** [comment]
This was reasonably adjusted under #209 which seemed reasonable, so adding a flag for legacy model rounding that we can use to preserve predictions. We're at the point we need to think about regression testing in the future I reckon @bnubald

**Comment by JimCircadian** [comment]
With n_filters_factor and legacy_rounding true / false

```
{64: 92, 128: 184, 256: 368, 512: 737}
{64: 92, 128: 184, 256: 368, 512: 736}
```
