### ISSUE TITLE
Training run crash: Tensorflow/Keras changes

### ISSUE THREAD

**Issue by bnubald** [icenet-ai/icenet#238]
* IceNet version: v0.2.7/v0.2.8a1 (Highly likely older versions as well)
* Python version: 3.11
* Operating System: Linux

### Description

Running training causes an error in the Tensorflow with latest version (v2.16.1) in the best checkpoint generation part.

### What I Did

```bash
Traceback (most recent call last):
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.8/bin/icenet_train", line 33, in <module>
    sys.exit(load_entry_point('icenet', 'console_scripts', 'icenet_train')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/hpcdata/users/username/git/icenet/icenet/icenet/model/train.py", line 437, in main
    train_model(args.run_name,
  File "/data/hpcdata/users/username/git/icenet/icenet/icenet/model/train.py", line 122, in train_model
    ModelCheckpoint(filepath=weights_path,
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.8/lib/python3.11/site-packages/keras/src/callbacks/model_checkpoint.py", line 191, in __init__
    raise ValueError(
ValueError: The filepath provided must end in `.keras` (Keras model format). Received: filepath=./results/networks/tutorial_south_ensemble/tutorial_south_ensemble.network_tutorial_pipeline_south.42.h5
```

**Comment by bnubald** [comment]
Issue caused by install of Keras >= 3 with latest Tensorflow (2.16.1)

`pip install icenet` installs the latest version of tensorflow (2.16.1), and also Keras>=3.

Refer to Keras docs here:
https://keras.io/getting_started/

> From TensorFlow 2.0 to TensorFlow 2.15 (included), doing pip install tensorflow will also install the corresponding version of Keras 2 – for instance, pip install tensorflow==2.14.0 will install keras==2.14.0. That version of Keras is then available via both import keras and from tensorflow import keras (the [tf.keras](https://www.tensorflow.org/api_docs/python/tf/keras) namespace).
>
> Starting with TensorFlow 2.16, doing pip install tensorflow will install Keras 3. When you have TensorFlow >= 2.16 and Keras 3, then by default from tensorflow import keras ([tf.keras](https://www.tensorflow.org/api_docs/python/tf/keras)) will be Keras 3.
>
> Meanwhile, the legacy Keras 2 package is still being released regularly and is available on PyPI as tf_keras (or equivalently tf-keras – note that - and _ are equivalent in PyPI package names). To use it, you can install it via pip install tf_keras then import it via import tf_keras as keras.

Keras 3 only supports exporting full model to a `.keras` file, and not the legacy `.h5`.

For v0.2.8 release, pinning tensorflow is probably easiest.

But, note to review for future @JimCircadian?
