### ISSUE TITLE
Error when generating some predictions

### ISSUE THREAD

**Issue by bnubald** [icenet-ai/icenet#303]
* IceNet version: 0.2.9_dev
* Python version: 3.11.8
* Operating System: CentOS 7 x64

### Description

When attempting to generate forecast prediction with `forecast_init_date=2022-11-30` for 2022-12-01 to 2023-03-02 by linking to previously downloaded data store, I'm getting the following error:

```bash
[30-12-24 22:18:04 :DEBUG   ] - GDAL data found in package: path='/data/hpcdata/users/username/miniconda3/envs/icenet0.2.9_dev/lib/python3.11/site-packages/rasterio/gdal_data'.
Traceback (most recent call last):
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.9_dev/lib/python3.11/site-packages/xarray/core/dataset.py", line 1348, in _construct_dataarray
    variable = self._variables[name]
               ~~~~~~~~~~~~~~~^^^^^^
KeyError: 'lambert_azimuthal_equal_area'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.9_dev/lib/python3.11/site-packages/xarray/core/concat.py", line 561, in _dataset_concat
    vars = ensure_common_dims([ds[name].variable for ds in datasets])
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.9_dev/lib/python3.11/site-packages/xarray/core/concat.py", line 561, in <listcomp>
    vars = ensure_common_dims([ds[name].variable for ds in datasets])
                               ~~^^^^^^
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.9_dev/lib/python3.11/site-packages/xarray/core/dataset.py", line 1439, in __getitem__
    return self._construct_dataarray(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.9_dev/lib/python3.11/site-packages/xarray/core/dataset.py", line 1350, in _construct_dataarray
    _, name, variable = _get_virtual_variable(self._variables, name, self.dims)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.9_dev/lib/python3.11/site-packages/xarray/core/dataset.py", line 186, in _get_virtual_variable
    raise KeyError(key)
KeyError: 'lambert_azimuthal_equal_area'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.9_dev/bin/icenet_process_era5", line 33, in <module>
    sys.exit(load_entry_point('icenet', 'console_scripts', 'icenet_process_era5')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/hpcdata/users/username/git/icenet/icenet/icenet/data/processors/era5.py", line 40, in main
    era5.process()
  File "/data/hpcdata/users/username/git/icenet/icenet/icenet/data/process.py", line 132, in process
    self._save_variable(var_name, var_suffix)
  File "/data/hpcdata/users/username/git/icenet/icenet/icenet/data/process.py", line 245, in _save_variable
    da = self._open_dataarray_from_files(var_name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/hpcdata/users/username/git/icenet/icenet/icenet/data/process.py", line 349, in _open_dataarray_from_files
    ds = xr.open_mfdataset(
         ^^^^^^^^^^^^^^^^^^
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.9_dev/lib/python3.11/site-packages/xarray/backends/api.py", line 1013, in open_mfdataset
    combined = _nested_combine(
               ^^^^^^^^^^^^^^^^
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.9_dev/lib/python3.11/site-packages/xarray/core/combine.py", line 365, in _nested_combine
    combined = _combine_nd(
               ^^^^^^^^^^^^
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.9_dev/lib/python3.11/site-packages/xarray/core/combine.py", line 239, in _combine_nd
    combined_ids = _combine_all_along_first_dim(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.9_dev/lib/python3.11/site-packages/xarray/core/combine.py", line 275, in _combine_all_along_first_dim
    new_combined_ids[new_id] = _combine_1d(
                               ^^^^^^^^^^^^
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.9_dev/lib/python3.11/site-packages/xarray/core/combine.py", line 298, in _combine_1d
    combined = concat(
               ^^^^^^^
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.9_dev/lib/python3.11/site-packages/xarray/core/concat.py", line 248, in concat
    return _dataset_concat(
           ^^^^^^^^^^^^^^^^
  File "/data/hpcdata/users/username/miniconda3/envs/icenet0.2.9_dev/lib/python3.11/site-packages/xarray/core/concat.py", line 563, in _dataset_concat
    raise ValueError(f"{name!r} is not present in all datasets.")
ValueError: 'lambert_azimuthal_equal_area' is not present in all datasets.
```

Checking for issue, looks like the 2022 ERA5 data downloads (not just the `uas` variable) have an additional `lambert_azimuthal_equal_area` variable causing xarray's `open_mfdataset` to fail:

```bash
❯ ./data/era5/south/uas/2021.nc
time                     Dataset {365}
uas                      Dataset {365, 432, 432}
xc                       Dataset {432}
yc                       Dataset {432}

❯ ./data/era5/south/uas/2022.nc
lambert_azimuthal_equal_area Dataset {SCALAR}
time                     Dataset {365}
uas                      Dataset {365, 432, 432}
xc                       Dataset {432}
yc                       Dataset {432}

❯ ./data/era5/south/uas/2023.nc
time                     Dataset {359}
uas                      Dataset {359, 432, 432}
xc                       Dataset {432}
yc                       Dataset {432}

❯ ./data/era5/south/uas/2024.nc
time                     Dataset {359}
uas                      Dataset {359, 432, 432}
xc                       Dataset {432}
yc                       Dataset {432}
```

### Potential Solution

@JimCircadian Looking through icenet codebase, in any case that the `lambert_azimuthal_equal_area` variable is found, it just seems to be dropped and not used, do we need to read this variable in? or, can we drop it along with the `lat` and `lon` variables here?:

https://github.com/icenet-ai/icenet/blob/f1285368eb731ed473c6b574b1d48ae574a8c01e/icenet/data/process.py#L349-L365

**Comment by JimCircadian** [comment]
We'll probably need to discuss slightly more, but it should be fine to drop. It's usually required for processing of the EASE grids properly, but in the case of running icenet based on that source data store, it doesn't need to be there so can be safely omitted.

**Comment by bnubald** [comment]
Closing since fixed in v0.2.9_dev branch.
