### ISSUE TITLE
Allow subsetting of plots to region

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet#80]
* IceNet version: 0.2.0

### Description

Add the ability to subset a region for analysis within `icenet_plot` commands. This can be trivial to begin with, with a region specified by a bounding box in the form `--region x1,y1,x2,y2`

**Comment by JimCircadian** [comment]
Good feature add is to make masks indexable by region:

```
Traceback (most recent call last):
  File "/home/jambyr/anaconda3/envs/icenet/bin/icenet_plot_sic_error", line 33, in <module>
    sys.exit(load_entry_point('icenet', 'console_scripts', 'icenet_plot_sic_error')())
  File "/home/jambyr/code/ai-lab/icenet/icenet/icenet/plotting/forecast.py", line 287, in sic_error
    fc, obs, masks = process_regions(args.region, [fc, obs, masks])
  File "/home/jambyr/code/ai-lab/icenet/icenet/icenet/plotting/forecast.py", line 57, in process_regions
    data[idx] = arr[y1:y2, x1:x2]
TypeError: 'Masks' object is not subscriptable
```

**Comment by JimCircadian** [comment]
`icenet_plot_sic_error -v -r 100,100,300,300 -o ./sictest.mp4 south eventattr_south.nc 2017-02-24`
produced
![Screenshot_2023-02-02_09-41-08](https://user-images.githubusercontent.com/731727/216288465-32ca9d99-72af-4ec7-9b8e-7691b112e883.png)

and

`icenet_plot_bin_accuracy -r 100,100,200,200 -o ./test.png south eventattr_south.nc 2017-02-28`

with or without regions produced

![test](https://user-images.githubusercontent.com/731727/216299859-0c6e7e1a-54c5-41c5-a6eb-8fd8c0696b01.png)
![test2](https://user-images.githubusercontent.com/731727/216299867-f531cd2d-5ff6-489d-851e-225a29bda88b.png)
