### ISSUE TITLE
Fixing hres oriented runthrough

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet#82]
* IceNet version: 0.2.1

### Description

As they've not been in general use, it appears some HRES commands have not been correctly updated. These need fixing through running of an exemplar workflow

### What I Did

```
icenet_process_hres -r processed/current_north/era5/north     $PROC_ARGS_ERA5 -v -l 1     -ts $DATE -te $DATE     hrestest_north north

[26-01-23 13:53:30 :INFO    ] - Writing configuration to ./loader.hrestest_north.json
Traceback (most recent call last):
  File "/data/hpcdata/users/jambyr/miniconda3/envs/icenet/bin/icenet_process_hres", line 33, in <module>
    sys.exit(load_entry_point('icenet', 'console_scripts', 'icenet_process_hres')())
  File "/data/hpcdata/users/jambyr/icenet/icenet.blue/icenet/data/processors/hres.py", line 52, in main
    linear_trend_days=args.forecast_days,
AttributeError: 'Namespace' object has no attribute 'forecast_days'
```

If this mapping is wrong, there'll likely be others, so will fix under this issue and get the HRES workflow running again.

**Comment by JimCircadian** [comment]
Should have referenced it, but this is to enable further conclusion of the accumulated var issue in #52
